services:
  node1:
    image: williamyeh/ansible:ubuntu18.04
    container_name: ansible-node1
    command: sleep infinity
    volumes:
      - ./ansible:/ansible
    tty: true

  node2:
    build: ./node-image
    container_name: ansible-node2
    ports:
      - "9081:80"   # http://localhost:8081
    tty: true

  node3:
    build: ./node-image
    container_name: ansible-node3
    ports:
      - "9082:80"   # http://localhost:8092 (changed from 8082 to avoid conflict)
    tty: true

